version: "3.9"

services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
    container_name: nba-backend
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
    container_name: nba-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
